### ISSUE TITLE
chiff ssh-keygen error

### ISSUE THREAD

**Issue by kt-git** [chiff-app/chiff-cli#24]
After installing chiff-cli via pipx and pairing it with the chiff android app successfully, I attempted to do a "chiff ssh-keygen -n Pixel7Pro", but received a python error as follows:

kevin@Stealth:~$ chiff ssh-keygen -n Pixel7Pro
Requesting to generate new SSH key Pixel7Pro
Traceback (most recent call last):
  File "/home/kevin/.local/bin/chiff", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/chiff/main.py", line 344, in create_ssh_key
    response = session.send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/.local/share/pipx/venvs/chiff/lib/python3.12/site-packages/chiff/session.py", line 57, in send_request
    request_id = randint(0, 1e9)
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 312, in randrange
    istop = _index(stop)
            ^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

**Comment by bas-d** [comment]
Thanks for notifying, apparently python 3.12 starts throwing error when float is passed to `randint`. Should be fixed in version 0.3.1.

**Comment by kt-git** [comment]
Just confirming this worked, I'm now using chiff-cli successfully and doing successful pulls from GitHub with chiff fingerprint verification.  Works great!
